# Generated by Django 3.0.4 on 2020-03-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='obiect_id',
            new_name='object_id',
        ),
    ]
